#!/usr/bin/php
<?php

/** 
 * Собрка воедино всех JS и CSS файлов:
 * cd /home/mathilde/www/mazepa.us/ && ./exe/compile 
 * ./exe/compile   - сборка с минимизацией 
 * ./exe/compile s - простая сборка без минимизации 
 */ 

$css = [
	"static/css/mazepa.css",
	"static/css/waves.css",
	"static/css/icons.css",
	"static/css/jelly.css",
	"static/css/simptip.css"
];

$js = [
	''        => ['lib/jquery-2.1.4.min','app','lib/waves'],
	'about'   => ['lib/jquery-2.1.4.min','app','lib/waves','lib/fsvs.bundle','about'],
	'album'   => ['lib/jquery-2.1.4.min','app','lib/waves','lib/photoswipe.min','lib/photoswipe-ui-default.min','media'],
	'gallery' => ['lib/jquery-2.1.4.min','app','lib/waves','media'],
	'stats'   => ['lib/jquery-2.1.4.min','app','lib/d3.min','lib/cal-heatmap.min','stats'],
	'index'   => ['lib/jquery-2.1.4.min','app','lib/waves','lib/jquery-ui.min', 'index'],
	'invite'  => ['lib/jquery-2.1.4.min','app','lib/waves','lib/jquery.ui.widget','lib/jquery.iframe-transport','lib/jquery.fileupload','invite'],
	'root'    => ['lib/jquery-2.1.4.min','app','lib/waves','lib/jquery.ui.widget','lib/jquery.iframe-transport','lib/jquery.fileupload','lib/jquery-ui.min','lib/jquery.knob','lib/root.upload-init','lib/qr','root']
];

include('exe/Minifier.php');

// JS
echo "\n> JS...\n";
exec("rm -f cache/*.js");
foreach ($js as $result => $files) {
	$f = "cache/@{$result}.js";
	exec("cat static/js/".implode(".js static/js/", $files).".js > $f");
	file_put_contents($f, Minifier::minify( file_get_contents($f) ));
	echo "> $f\n";
}

// CSS
echo "> main css\n";
exec("rm -f cache/*.css");
exec("cat ". implode(" ", $css). " > cache/@style.css\n");
exec("ls cache/*.css", $exec);
foreach ($exec as $f) file_put_contents($f, M(file_get_contents($f), 'cssminifier.com'));

// ROOT CSS
echo "> root css\n";
exec("cat static/css/root.css > cache/@root.css\n");
file_put_contents("cache/@root.css", M(file_get_contents("cache/@root.css"), 'cssminifier.com'));

// STAT CSS
echo "> stat css";
exec("cat static/css/cal-heatmap.css static/css/stats.css > cache/@stats.css\n");
file_put_contents("cache/@stats.css", M(file_get_contents("cache/@stats.css"), 'cssminifier.com'));

echo "\n[OK]\n";

function M($e, $url = 'javascript-minifier.com'){
	if (@$_SERVER['argv'][1] == 's') return $e;
	$data = http_build_query(['input' => $e]);
	exec("curl -s 'http://$url/raw' --data '{$data}'", $exec);
	$R = implode('', $exec);
	return $R == '' ? 'console.log("Fail")' : $R;
}
